/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedesignRouteImport } from './routes/redesign'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EditRouteImport } from './routes/edit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSaveHistoryRouteImport } from './routes/api/save-history'
import { Route as ApiListImagesRouteImport } from './routes/api/list-images'
import { Route as ApiListHistoryRouteImport } from './routes/api/list-history'
import { Route as ApiJudgeGenerationRouteImport } from './routes/api/judge-generation'
import { Route as ApiGetHistoryForImageRouteImport } from './routes/api/get-history-for-image'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiImagesFilenameRouteImport } from './routes/api/images.$filename'
import { Route as ApiImagesModifiedFilenameRouteImport } from './routes/api/images-modified.$filename'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const RedesignRoute = RedesignRouteImport.update({
  id: '/redesign',
  path: '/redesign',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveHistoryRoute = ApiSaveHistoryRouteImport.update({
  id: '/api/save-history',
  path: '/api/save-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListImagesRoute = ApiListImagesRouteImport.update({
  id: '/api/list-images',
  path: '/api/list-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListHistoryRoute = ApiListHistoryRouteImport.update({
  id: '/api/list-history',
  path: '/api/list-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJudgeGenerationRoute = ApiJudgeGenerationRouteImport.update({
  id: '/api/judge-generation',
  path: '/api/judge-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetHistoryForImageRoute = ApiGetHistoryForImageRouteImport.update({
  id: '/api/get-history-for-image',
  path: '/api/get-history-for-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesFilenameRoute = ApiImagesFilenameRouteImport.update({
  id: '/api/images/$filename',
  path: '/api/images/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesModifiedFilenameRoute =
  ApiImagesModifiedFilenameRouteImport.update({
    id: '/api/images-modified/$filename',
    path: '/api/images-modified/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/history': typeof HistoryRoute
  '/redesign': typeof RedesignRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/get-history-for-image': typeof ApiGetHistoryForImageRoute
  '/api/judge-generation': typeof ApiJudgeGenerationRoute
  '/api/list-history': typeof ApiListHistoryRoute
  '/api/list-images': typeof ApiListImagesRoute
  '/api/save-history': typeof ApiSaveHistoryRoute
  '/api/upload': typeof ApiUploadRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/images-modified/$filename': typeof ApiImagesModifiedFilenameRoute
  '/api/images/$filename': typeof ApiImagesFilenameRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/history': typeof HistoryRoute
  '/redesign': typeof RedesignRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/get-history-for-image': typeof ApiGetHistoryForImageRoute
  '/api/judge-generation': typeof ApiJudgeGenerationRoute
  '/api/list-history': typeof ApiListHistoryRoute
  '/api/list-images': typeof ApiListImagesRoute
  '/api/save-history': typeof ApiSaveHistoryRoute
  '/api/upload': typeof ApiUploadRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/images-modified/$filename': typeof ApiImagesModifiedFilenameRoute
  '/api/images/$filename': typeof ApiImagesFilenameRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/history': typeof HistoryRoute
  '/redesign': typeof RedesignRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/get-history-for-image': typeof ApiGetHistoryForImageRoute
  '/api/judge-generation': typeof ApiJudgeGenerationRoute
  '/api/list-history': typeof ApiListHistoryRoute
  '/api/list-images': typeof ApiListImagesRoute
  '/api/save-history': typeof ApiSaveHistoryRoute
  '/api/upload': typeof ApiUploadRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/images-modified/$filename': typeof ApiImagesModifiedFilenameRoute
  '/api/images/$filename': typeof ApiImagesFilenameRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edit'
    | '/history'
    | '/redesign'
    | '/api/generate-image'
    | '/api/get-history-for-image'
    | '/api/judge-generation'
    | '/api/list-history'
    | '/api/list-images'
    | '/api/save-history'
    | '/api/upload'
    | '/demo/tanstack-query'
    | '/api/images-modified/$filename'
    | '/api/images/$filename'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/edit'
    | '/history'
    | '/redesign'
    | '/api/generate-image'
    | '/api/get-history-for-image'
    | '/api/judge-generation'
    | '/api/list-history'
    | '/api/list-images'
    | '/api/save-history'
    | '/api/upload'
    | '/demo/tanstack-query'
    | '/api/images-modified/$filename'
    | '/api/images/$filename'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/edit'
    | '/history'
    | '/redesign'
    | '/api/generate-image'
    | '/api/get-history-for-image'
    | '/api/judge-generation'
    | '/api/list-history'
    | '/api/list-images'
    | '/api/save-history'
    | '/api/upload'
    | '/demo/tanstack-query'
    | '/api/images-modified/$filename'
    | '/api/images/$filename'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditRoute: typeof EditRoute
  HistoryRoute: typeof HistoryRoute
  RedesignRoute: typeof RedesignRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGetHistoryForImageRoute: typeof ApiGetHistoryForImageRoute
  ApiJudgeGenerationRoute: typeof ApiJudgeGenerationRoute
  ApiListHistoryRoute: typeof ApiListHistoryRoute
  ApiListImagesRoute: typeof ApiListImagesRoute
  ApiSaveHistoryRoute: typeof ApiSaveHistoryRoute
  ApiUploadRoute: typeof ApiUploadRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiImagesModifiedFilenameRoute: typeof ApiImagesModifiedFilenameRoute
  ApiImagesFilenameRoute: typeof ApiImagesFilenameRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redesign': {
      id: '/redesign'
      path: '/redesign'
      fullPath: '/redesign'
      preLoaderRoute: typeof RedesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-history': {
      id: '/api/save-history'
      path: '/api/save-history'
      fullPath: '/api/save-history'
      preLoaderRoute: typeof ApiSaveHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/list-images': {
      id: '/api/list-images'
      path: '/api/list-images'
      fullPath: '/api/list-images'
      preLoaderRoute: typeof ApiListImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/list-history': {
      id: '/api/list-history'
      path: '/api/list-history'
      fullPath: '/api/list-history'
      preLoaderRoute: typeof ApiListHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/judge-generation': {
      id: '/api/judge-generation'
      path: '/api/judge-generation'
      fullPath: '/api/judge-generation'
      preLoaderRoute: typeof ApiJudgeGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-history-for-image': {
      id: '/api/get-history-for-image'
      path: '/api/get-history-for-image'
      fullPath: '/api/get-history-for-image'
      preLoaderRoute: typeof ApiGetHistoryForImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$filename': {
      id: '/api/images/$filename'
      path: '/api/images/$filename'
      fullPath: '/api/images/$filename'
      preLoaderRoute: typeof ApiImagesFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images-modified/$filename': {
      id: '/api/images-modified/$filename'
      path: '/api/images-modified/$filename'
      fullPath: '/api/images-modified/$filename'
      preLoaderRoute: typeof ApiImagesModifiedFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditRoute: EditRoute,
  HistoryRoute: HistoryRoute,
  RedesignRoute: RedesignRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGetHistoryForImageRoute: ApiGetHistoryForImageRoute,
  ApiJudgeGenerationRoute: ApiJudgeGenerationRoute,
  ApiListHistoryRoute: ApiListHistoryRoute,
  ApiListImagesRoute: ApiListImagesRoute,
  ApiSaveHistoryRoute: ApiSaveHistoryRoute,
  ApiUploadRoute: ApiUploadRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiImagesModifiedFilenameRoute: ApiImagesModifiedFilenameRoute,
  ApiImagesFilenameRoute: ApiImagesFilenameRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
