/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiModifyImageRouteImport } from './routes/api/modify-image'
import { Route as ApiListImagesRouteImport } from './routes/api/list-images'
import { Route as ApiImagesFilenameRouteImport } from './routes/api/images.$filename'
import { Route as ApiImagesModifiedFilenameRouteImport } from './routes/api/images-modified.$filename'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModifyImageRoute = ApiModifyImageRouteImport.update({
  id: '/api/modify-image',
  path: '/api/modify-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListImagesRoute = ApiListImagesRouteImport.update({
  id: '/api/list-images',
  path: '/api/list-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesFilenameRoute = ApiImagesFilenameRouteImport.update({
  id: '/api/images/$filename',
  path: '/api/images/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesModifiedFilenameRoute =
  ApiImagesModifiedFilenameRouteImport.update({
    id: '/api/images-modified/$filename',
    path: '/api/images-modified/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/list-images': typeof ApiListImagesRoute
  '/api/modify-image': typeof ApiModifyImageRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/images-modified/$filename': typeof ApiImagesModifiedFilenameRoute
  '/api/images/$filename': typeof ApiImagesFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/list-images': typeof ApiListImagesRoute
  '/api/modify-image': typeof ApiModifyImageRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/images-modified/$filename': typeof ApiImagesModifiedFilenameRoute
  '/api/images/$filename': typeof ApiImagesFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/list-images': typeof ApiListImagesRoute
  '/api/modify-image': typeof ApiModifyImageRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/images-modified/$filename': typeof ApiImagesModifiedFilenameRoute
  '/api/images/$filename': typeof ApiImagesFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/list-images'
    | '/api/modify-image'
    | '/api/upload'
    | '/api/images-modified/$filename'
    | '/api/images/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/list-images'
    | '/api/modify-image'
    | '/api/upload'
    | '/api/images-modified/$filename'
    | '/api/images/$filename'
  id:
    | '__root__'
    | '/'
    | '/api/list-images'
    | '/api/modify-image'
    | '/api/upload'
    | '/api/images-modified/$filename'
    | '/api/images/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiListImagesRoute: typeof ApiListImagesRoute
  ApiModifyImageRoute: typeof ApiModifyImageRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiImagesModifiedFilenameRoute: typeof ApiImagesModifiedFilenameRoute
  ApiImagesFilenameRoute: typeof ApiImagesFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/modify-image': {
      id: '/api/modify-image'
      path: '/api/modify-image'
      fullPath: '/api/modify-image'
      preLoaderRoute: typeof ApiModifyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/list-images': {
      id: '/api/list-images'
      path: '/api/list-images'
      fullPath: '/api/list-images'
      preLoaderRoute: typeof ApiListImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$filename': {
      id: '/api/images/$filename'
      path: '/api/images/$filename'
      fullPath: '/api/images/$filename'
      preLoaderRoute: typeof ApiImagesFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images-modified/$filename': {
      id: '/api/images-modified/$filename'
      path: '/api/images-modified/$filename'
      fullPath: '/api/images-modified/$filename'
      preLoaderRoute: typeof ApiImagesModifiedFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiListImagesRoute: ApiListImagesRoute,
  ApiModifyImageRoute: ApiModifyImageRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiImagesModifiedFilenameRoute: ApiImagesModifiedFilenameRoute,
  ApiImagesFilenameRoute: ApiImagesFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
